{% if builder == "gradle" %}
FROM gradle:8.8.0 AS build

COPY --chown=gradle:gradle . .

{% for command in commands %}
RUN {{ command }}
{% endfor %}

FROM openjdk:{{ jdk_version }}-jdk-slim

ENV TZ=Asia/Seoul

COPY --from=build {{ output_dir }} app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
{% endif %}
