{% if builder == "gradle" %}
FROM openjdk:{{ jdk_version }}-jdk-slim AS build
COPY . .

RUN chmod +x gradlew

{% for command in commands %}
RUN {{ command }}
{% endfor %}

FROM openjdk:{{ jdk_version }}-jdk-slim

# Set the time zone
ENV TZ=Asia/Seoul

COPY --from=build {{ output_dir }} app.jar

ENTRYPOINT ["java", "-jar", "/app.jar"]
{% endif %}
