format_version: 10
pipelines:
  deploy-{{ .Values.name }}:
    group: {{ .Values.club }}
    materials:
      git:
        url: https://github.com/{{ .Values.organization }}/{{ .Values.repository }}.git
        branch: {{ .Values.branch }}
        shallow_clone: false
    stages:
      - name: Build_and_Push
        jobs:
          - name: Get_Image_Tag
            tasks:
              - exec:
                  run_if: passed
                  command: /bin/bash
                  arguments:
                    - -c
                    - |
                      RANDOM_KEY=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 8 | head -n 1)
                      export VERSION_TAG="{{ .Values.environment }}-${RANDOM_KEY}"
                      echo "VERSION_TAG=$VERSION_TAG" > go_env.properties
            artifacts:
              - build:
                  source: go_env.properties
                  destination: .
          - name: Docker_Build_and_Push
            tasks:
              - exec:
                  run_if: passed
                  command: /bin/bash
                  arguments:
                    - -c
                    - |
                      source go_env.properties
                      repo="${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO_NAME}:${VERSION_TAG}"
                      docker build -t "$repo" "$BASE_URL"
                      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                      docker push $repo
