format_version: 10
pipelines:
  build-{{ .Values.name }}:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/{{ .Values.organization }}/{{ .Values.repository }}
        shallow_clone: false
        auto_update: true
        branch: {{ .Values.branch }}
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: ./build.sh
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: ./deploy.sh