format_version: 10
pipelines:
  build-{{ .Values.name }}:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/{{ .Values.organization }}/{{ .Values.repository }}
        shallow_clone: false
        auto_update: true
        branch: {{ .Values.branch }}
    stages:
      - build:
          jobs:
            build:
              resources:
                - build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o docker_build.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo/v2/script/docker_build.sh
                        chmod +x docker_build.sh
                        ./docker_build.sh {{ .Values.environment }} {{ .Values.name }}
      - deploy:
          jobs:
            deploy:
              resources:
                - deploy
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o resource_deploy.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo/v2/script/resource_deploy.sh
                        chmod +x resource_deploy.sh
                        ./resource_deploy.sh {{ .Values.name }} {{ .Values.environment }} ${{ .Values.name }}_REPOSITORY 
