---
# Source: gocd/templates/deploy.yaml
format_version: 10
pipelines:
  build-maeumgagym:
    group: maeumgagym
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/MaeumGaGym/MaeumGaGym_Backend
        shallow_clone: false
        auto_update: true
        branch: develop
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: ./build.sh
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: ./deploy.sh
