---
# Source: gocd/templates/deploy.yaml
format_version: 10
pipelines:
  build-maeumgagym:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/MaeumGaGym/MaeumGaGym_Backend
        shallow_clone: false
        auto_update: true
        branch: develop
    stages:
      - build:
          jobs:
            build:
              resources:
                - build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o docker_build.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo/v2/script/docker_build.sh
                        chmod +x docker_build.sh
                        ./docker_build.sh stag maeumgagym
              artifacts:
                - build_result.env
      - deploy:
          jobs:
            deploy:
              resources:
                - deploy
              tasks:
                - fetch:
                    artifact: build/build/build_result.env
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o resource_deploy.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo/v2/script/resource_deploy.sh
                        chmod +x resource_deploy.sh
                        ./resource_deploy.sh maeumgagym stag $maeumgagym_REPOSITORY
