{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    project: {{ .Values.name }}
    test: test
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:      
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
        sidecar.istio.io/proxyCPU: "5m"
        sidecar.istio.io/proxyMemory: "128Mi"
        {{- if eq .Values.language "java"}}
        instrumentation.opentelemetry.io/inject-java: "true"
        {{- end }}
      labels:
        tags.datadoghq.com/env: {{ .Values.environment }}
        tags.datadoghq.com/service: {{ $fullname }}
        app: {{ $fullname }}
        project: {{ .Values.name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ $fullname }}
              topologyKey: "kubernetes.io/hostname"
      {{- if eq $fullname "project-secret-manager-be-prod" }}
      priorityClassName: system-cluster-critical
      {{- end }}
      nodeSelector:
        Karpenter: enabled
      tolerations:
      - effect: "NoSchedule"
        key: xquare/server
        operator: "Equal"
        value: "true"
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ $fullname }}
          image: 786584124104.dkr.ecr.ap-northeast-2.amazonaws.com/{{ .Values.name }}:{{ .Values.environment }}-{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
          - secretRef:
              name: {{ $fullname }}
          resources:
            requests:
              memory: "2000Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2000Mi"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
