{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Valeus.club }}-{{ .Values.environment }}
  name: {{ $fullname }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullname }}
