{{- $fullname := (printf "%s-%s" .Values.name .Values.environment) }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Valeus.club }}-{{ .Values.environment }}
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    project: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  selector:
    app: {{ $fullname }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
    - name: port
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
