---
# Source: gocd/templates/deploy.yaml
format_version: 10
pipelines:
  build-gocd-test:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/team-xquare/gocd-test-repository
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: ./docker_build.sh
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: ./deploy.sh
