---
# Source: gocd/templates/deploy.yaml
format_version: 10
pipelines:
  build-gocd-test:
    group: xquare
    environment_variables:

    label_template: "${git[:7]}"
    materials:
      git:
        git: https://github.com/team-xquare/gocd-test-repository
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        curl -o docker_build.sh https://raw.githubusercontent.com/team-xquare/xquare-gitops-repo/v2/script/docker_build.sh
                        chmod +x docker_build.sh
                        sudo sh docker_build.sh gocd-test stag
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: ./deploy.sh
